name: forest_classifier
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - babel=2.8.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - cmarkgfm=0.4.2
  - colorama=0.4.4
  - commonmark=0.9.1
  - cryptography=3.1.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cython=0.29.21
  - dataclasses=0.7
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - future=0.18.2
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.5.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.2
  - ninja=1.10.1
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11.0.4
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - pkginfo=1.6.0
  - pluggy=0.13.1
  - prometheus_client=0.8.0
  - prompt_toolkit=1.0.15
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - py=1.9.0
  - pycparser=2.20
  - pygments=2.7.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.1.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.7.0
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.0
  - readme_renderer=24.0
  - recommonmark=0.6.0
  - requests=2.24.0
  - requests-toolbelt=0.9.1
  - send2trash=1.5.0
  - setuptools=50.3.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sphinx=3.2.1
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.33.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.1
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=4.3.3
  - twine=3.2.0
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - annoy==1.17.0
    - astor==0.8.1
    - bump2version==1.0.1
    - bumpversion==0.6.0
    - gast==0.4.0
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - keras==2.3.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keras-resnet==0.2.0
    - keras-retinanet==0.5.1
    - markdown==3.3.3
    - opencv-python==4.4.0.46
    - progressbar2==3.53.1
    - protobuf==3.13.0
    - pydot==1.4.1
    - python-utils==2.4.0
    - reverse-geocode==1.4.1
    - scipy==1.5.3
    - slidingwindow==0.0.14
    - sphinx-markdown-tables==0.0.15
    - split-folders==0.4.3
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1